claim_limit: 3
claim_block_limit: 5000
initial_claim_size: 7 # Minimum value of 3
minimum_partition_size: 3 # Minimum value of 3
distance_between_claims: 1
visualiser_hide_delay_period: 2 # Value in seconds
visualiser_refresh_period: 1 # Value in seconds
plugin_language: EN
right_click_harvest: true
#NOT COMPLETED
# EN - Original
# RU - Machine translation (Temporary)
# DE - Machine translation (Temporary)
# CN - Machine translation (Temporary)
# add more lang_<?>.yml files in this folder and change plugin_language: <?>